### ISSUE TITLE
sid is not unique on virus & value error on double tax id

### ISSUE THREAD

**Issue by matthiaskoenig** [janekg89/flutype_webapp#127]
I can create multiple viruses with an empty sid.
The sid should identify the virus, the taxonomy id is additional information.

When creating entries with duplicated tax id it gives ValueErrors.
```
ValueError at /viruses/new/
The view flutype.views.virus_new didn't return an HttpResponse object. It returned None instead.
```

**Comment by janekg89** [comment]
resolved in recent commits
