### ISSUE TITLE
Why is the tutorial not listed in studies?

### ISSUE THREAD

**Issue by matthiaskoenig** [janekg89/flutype_webapp#87]
The tutorial is also a study. Why is this study only accessible via the tutorial menu, but not listed in the studies?
This should be part of the studies.

**Comment by janekg89** [comment]
I added a field "hidden" to the study and measurement model. All the tutorial data, which I partially invented, I set as hidden. Right now they are only reachable through the "tutorial data"  tab. I thought this makes sense ?

**Comment by matthiaskoenig** [comment]
This makes sense. 
Just show the tutorial for now in studies and measurements, i.e., no filtering in the views. Later on we can hide it again, but for debugging while the interface is changing it makes sense to see the tutorial study.
